version: "2"

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "5005:5005"
    volumes:
      - ./build/libs:/code
    links:
      - redis-server
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -jar -Dspring.profiles.active=dev /app/api.jar

  redis-server:
    image: redis:3.2
    ports:
      - "6379:6379"

  redis-commander:
    image: tenstartups/redis-commander
    command: --redis-host redis-server
    links:
      - redis-server
    ports:
      - "8081:8081"
